import js from '@eslint/js';
import globals from 'globals';
import prettierConfig from 'eslint-config-prettier';

export default [
    { ignores: ['assets/js/vendor/**', 'assets/js/admin/**'] },
    js.configs.recommended,
    prettierConfig,
    {
        files: ['assets/js/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                ...globals.browser,

                // ── CDN Libraries ──
                lucide: 'readonly',
                html2pdf: 'readonly',
                QRCode: 'readonly',
                qrcode: 'readonly',

                // ── Tiptap (exposed on window via tiptap.bundle.js) ──
                TiptapEditor: 'readonly',
                TiptapStarterKit: 'readonly',
                TiptapPlaceholder: 'readonly',
                TiptapLink: 'readonly',
                TiptapUnderline: 'readonly',
                TiptapHighlight: 'readonly',
                TiptapTable: 'readonly',
                TiptapTableRow: 'readonly',
                TiptapTableCell: 'readonly',
                TiptapTableHeader: 'readonly',
                TiptapTaskList: 'readonly',
                TiptapTaskItem: 'readonly',
                TiptapBubbleMenu: 'readonly',

                // ── core/store.js — Data & Utilities ──
                DB: 'writable',
                CONFIG: 'writable',
                CLIENTS: 'writable',
                CUR: 'writable',
                saveTimer: 'writable',
                ctxTarget: 'writable',
                currentFilter: 'writable',
                currentSort: 'writable',
                lastSaveTime: 'writable',
                saveIndicatorTimer: 'writable',
                docTemplate: 'writable',
                sectionEditors: 'writable',
                paymentTermsEditor: 'writable',
                focusMode: 'writable',
                viewMode: 'writable',
                undoStack: 'writable',
                redoStack: 'writable',
                MAX_UNDO: 'readonly',
                persist: 'readonly',
                saveConfig: 'readonly',
                saveClients: 'readonly',
                cur: 'readonly',
                uid: 'readonly',
                activeDB: 'readonly',
                safeGetStorage: 'readonly',
                esc: 'readonly',
                escAttr: 'readonly',
                safeLsSet: 'readonly',
                sanitizeHtml: 'readonly',
                sanitizeDataUrl: 'readonly',
                isValidId: 'readonly',
                TAX_VALIDATORS: 'readonly',
                validateTaxId: 'readonly',
                fmtCur: 'readonly',
                fmtNum: 'readonly',
                fmtDate: 'readonly',
                timeAgo: 'readonly',
                rgbToHex: 'readonly',
                COUNTRY_CURRENCY: 'readonly',
                defaultCurrency: 'readonly',
                proposalValue: 'readonly',
                capitalize: 'readonly',
                nextPropNumber: 'readonly',
                taxLabel: 'readonly',
                COLORS: 'readonly',
                COLOR_NAMES: 'readonly',
                logoutApp: 'readonly',
                statusIcon: 'readonly',

                // ── core/utils.js ──
                DatePicker: 'readonly',
                datePickers: 'writable',
                autoResizeTextarea: 'readonly',
                initDatePickers: 'readonly',

                // ── core/theme.js ──
                getCurrentTheme: 'readonly',
                FONT_URLS: 'readonly',
                applyFont: 'readonly',

                // ── core/modals.js ──
                trapFocus: 'readonly',
                releaseFocus: 'readonly',
                openNewModal: 'readonly',
                pickNewModalColor: 'readonly',
                closeNewModal: 'readonly',
                toast: 'readonly',
                showLoading: 'readonly',
                hideLoading: 'readonly',
                confirmDialog: 'readonly',

                // ── core/shortcuts.js ──
                openShortcutsPanel: 'readonly',
                shortcutRow: 'readonly',

                // ── core/command.js ──
                openCommandPalette: 'readonly',
                closeCommandPalette: 'readonly',
                buildCommandItems: 'readonly',
                cmdRun: 'readonly',
                onCommandSearch: 'readonly',
                onCommandKeydown: 'readonly',

                // ── core/custom-select.js ──
                csel: 'readonly',
                cselOpen: 'readonly',
                cselToggle: 'readonly',
                _cselFilterMenu: 'readonly',
                cselFilter: 'readonly',
                cselGetValue: 'readonly',

                // ── core/router.js ──
                navigate: 'readonly',
                replaceUrl: 'readonly',
                handleRoute: 'readonly',
                render404: 'readonly',
                renderErrorPage: 'readonly',
                buildUrl: 'readonly',

                // ── core/support.js ──
                loadMyTickets: 'readonly',
                showTicketDetail: 'readonly',
                submitNewTicket: 'readonly',
                spSendReply: 'readonly',
                hasUnreadTickets: 'readonly',

                // ── core/plans.js ──
                PLAN_LIMITS: 'readonly',
                enforceLimit: 'readonly',
                checkLimit: 'readonly',
                showUpgradeModal: 'readonly',
                getCurrentPlan: 'readonly',
                getPlanBadge: 'readonly',
                trackEvent: 'readonly',

                // ── core/announcements.js ──
                checkAnnouncements: 'readonly',
                dismissAnnouncement: 'readonly',

                // ── core/completeness.js ──
                calcCompleteness: 'readonly',
                getCompletenessColor: 'readonly',
                buildCompletenessHtml: 'readonly',
                buildScoreBadge: 'readonly',
                showCompletenessDetail: 'readonly',
                navigateToTab: 'readonly',

                // ── core/sync.js ──
                syncTimer: 'writable',
                SYNC_DEBOUNCE: 'readonly',
                syncEnabled: 'readonly',
                syncAfterPersist: 'readonly',
                syncAfterSaveConfig: 'readonly',
                syncAfterSaveClients: 'readonly',
                pushProposals: 'readonly',
                pushConfig: 'readonly',
                pushClients: 'readonly',
                pushLibraries: 'readonly',
                pullFromCloud: 'readonly',
                pushToCloud: 'readonly',
                mergeProposals: 'readonly',
                mergeClients: 'readonly',

                // ── core/onboarding.js ──
                OB_COUNTRIES: 'readonly',
                obStep: 'writable',
                renderOnboarding: 'readonly',
                getObStepHtml: 'readonly',
                getCountryFields: 'readonly',
                onCountryChange: 'readonly',
                obNext: 'readonly',
                validateObTaxIds: 'readonly',
                obPrev: 'readonly',
                collectObStep: 'readonly',
                finishOb: 'readonly',
                renderColorSwatches: 'readonly',
                handleLogo: 'readonly',

                // ── core/team.js ──
                TEAM_COLORS: 'readonly',
                VALID_ROLES: 'readonly',
                initTeam: 'readonly',
                activeUser: 'readonly',
                updateSidebarUser: 'readonly',
                switchUser: 'readonly',
                addTeamMember: 'readonly',
                removeTeamMember: 'readonly',
                isAdmin: 'readonly',
                canEdit: 'readonly',
                userAvatar: 'readonly',
                showUserSwitcher: 'readonly',
                renderTeamSettings: 'readonly',
                showAddMemberModal: 'readonly',
                doAddMember: 'readonly',

                // ── core/supabase.js ──
                SUPABASE_URL: 'readonly',
                SUPABASE_ANON_KEY: 'readonly',
                sbClient: 'writable',
                sbSession: 'writable',
                initSupabase: 'readonly',
                sb: 'readonly',
                isLoggedIn: 'readonly',
                getAccessToken: 'readonly',
                getTokenExpiry: 'readonly',
                isTokenExpired: 'readonly',
                refreshToken: 'readonly',
                getValidToken: 'readonly',
                generateCsrfToken: 'readonly',
                validateCsrfToken: 'readonly',
                getUser: 'readonly',
                getUserProfile: 'readonly',
                getUserPlan: 'readonly',
                syncStatus: 'writable',
                setSyncStatus: 'readonly',

                // ── core/auth.js ──
                authMode: 'writable',
                initAuth: 'readonly',
                showOAuthRetryScreen: 'readonly',
                offlineBoot: 'readonly',
                onSignedIn: 'readonly',
                pullAndBoot: 'readonly',
                renderAuthScreen: 'readonly',
                getLoginHtml: 'readonly',
                getSignupHtml: 'readonly',
                getResetHtml: 'readonly',
                showAuthError: 'readonly',
                setAuthLoading: 'readonly',
                doLogin: 'readonly',
                doSignup: 'readonly',
                doGoogleLogin: 'readonly',
                doPasswordReset: 'readonly',
                skipAuth: 'readonly',
                doLogout: 'readonly',

                // ── core/autosave.js ──
                showSaveIndicator: 'readonly',
                updateSaveText: 'readonly',
                pushUndo: 'readonly',
                _viewerWarned: 'writable',
                dirty: 'readonly',
                undo: 'readonly',
                redo: 'readonly',

                // ── core/variables.js ──
                replaceVariables: 'readonly',
                VARIABLE_LIST: 'readonly',
                showInsertVariableDropdown: 'readonly',

                // ── views/nav.js ──
                destroyAllEditors: 'readonly',
                goNav: 'readonly',
                toggleMobileSidebar: 'readonly',
                closeMobileSidebar: 'readonly',
                toggleSidebar: 'readonly',
                toggleUserMenu: 'readonly',
                openGuide: 'readonly',
                openFeedbackModal: 'readonly',
                setFbTab: 'readonly',
                selectFbType: 'readonly',
                submitFeedback: 'readonly',
                initSidebarState: 'readonly',
                initKeyboardShortcuts: 'readonly',

                // ── views/dashboard.js ──
                buildDuesBanner: 'readonly',
                buildExpiryBanner: 'readonly',
                buildResumeCard: 'readonly',
                dismissExpiry: 'readonly',
                renderDashboard: 'readonly',
                toggleSort: 'readonly',
                sortProposals: 'readonly',

                // ── views/proposals.js ──
                renderPropTable: 'readonly',
                doQuickExport: 'readonly',
                quickPreview: 'readonly',
                showStatusMenu: 'readonly',
                setProposalStatus: 'readonly',
                setFilter: 'readonly',
                filterList: 'readonly',
                currentPage: 'writable',
                ITEMS_PER_PAGE: 'readonly',
                renderProposals: 'readonly',
                goPage: 'readonly',
                toggleSortProposals: 'readonly',
                showSortMenu: 'readonly',
                buildPagination: 'readonly',

                // ── views/clients.js ──
                INDIAN_STATES: 'readonly',
                SALUTATIONS: 'readonly',
                renderClients: 'readonly',
                matchClient: 'readonly',
                openAddClient: 'readonly',
                initStateDropdown: 'readonly',
                saveClient: 'readonly',
                editClient: 'readonly',
                delClient: 'readonly',
                showClientPicker: 'readonly',
                pickClient: 'readonly',
                showClientInsight: 'readonly',
                buildClientHistory: 'readonly',
                createProposalForClient: 'readonly',

                // ── views/settings.js ──
                openSettings: 'readonly',
                getCountryTaxHtml: 'readonly',
                buildAccountCard: 'readonly',
                renderSettings: 'readonly',
                DEFAULT_TEMPLATES: 'readonly',
                getEmailTemplates: 'readonly',
                renderEmailTemplates: 'readonly',
                addEmailTemplate: 'readonly',
                editEmailTemplate: 'readonly',
                deleteEmailTemplate: 'readonly',
                showTemplateModal: 'readonly',
                saveEmailTemplate: 'readonly',
                saveSettings: 'readonly',
                markInvalid: 'readonly',
                clearInvalid: 'readonly',
                exportData: 'readonly',
                importData: 'readonly',
                applyWhiteLabel: 'readonly',
                appName: 'readonly',

                // ── views/profile.js ──
                renderProfile: 'readonly',

                // ── views/analytics.js ──
                analyticsFilter: 'writable',
                _areaChartData: 'writable',
                getFilteredProposals: 'readonly',
                computeAnalytics: 'readonly',
                buildAreaChart: 'readonly',
                drawAreaChart: 'readonly',
                buildDonutChart: 'readonly',
                buildAnalyticsWidget: 'readonly',
                setAnalyticsFilter: 'readonly',

                // ── views/analytics-breakdowns.js ──
                breakdownTab: 'writable',
                openAnalyticsBreakdowns: 'readonly',
                setBreakdownTab: 'readonly',
                getBreakdownContent: 'readonly',
                getProposalValue: 'readonly',
                buildHBar: 'readonly',
                buildValueBreakdown: 'readonly',
                buildClientBreakdown: 'readonly',
                buildMonthBreakdown: 'readonly',
                buildTemplateBreakdown: 'readonly',
                exportAnalyticsReport: 'readonly',

                // ── views/kanban.js ──
                setViewMode: 'readonly',
                renderKanban: 'readonly',
                kanbanCard: 'readonly',
                initKanbanDrag: 'readonly',

                // ── editor/editor.js ──
                createEditor: 'readonly',
                migrateEditorContent: 'readonly',
                convertLegacyBlocks: 'readonly',
                loadEditor: 'readonly',
                refreshStatsBar: 'readonly',
                edTab: 'readonly',

                // ── editor/details.js ──
                renderDetails: 'readonly',
                updateExpiryWarning: 'readonly',
                toggleStatusMenu: 'readonly',
                setStatus: 'readonly',
                handleCoverPhoto: 'readonly',
                changeCoverPhoto: 'readonly',
                removeCoverPhoto: 'readonly',

                // ── editor/sections.js ──
                renderSections: 'readonly',
                initSectionEditors: 'readonly',
                initSingleSectionEditor: 'readonly',
                secBlockHtml: 'readonly',
                addSec: 'readonly',
                showAddSectionMenu: 'readonly',
                togSec: 'readonly',
                updSecName: 'readonly',
                delSec: 'readonly',
                initDrag: 'readonly',
                saveSectionToLib: 'readonly',
                DEFAULT_SECTIONS: 'readonly',
                openLibrary: 'readonly',
                setLibCat: 'readonly',
                setLibTab: 'readonly',
                filterLibrary: 'readonly',
                insertFromLib: 'readonly',

                // ── editor/structured-sections.js ──
                STRUCTURED_SECTION_DEFAULTS: 'readonly',
                structuredSecBlockHtml: 'readonly',
                testimonialFormHtml: 'readonly',
                caseStudyFormHtml: 'readonly',
                setRating: 'readonly',
                collectStructuredSection: 'readonly',
                buildTestimonialPdfHtml: 'readonly',
                buildCaseStudyPdfHtml: 'readonly',
                buildStructuredSectionPdf: 'readonly',

                // ── editor/section-packs.js ──
                SECTION_PACKS: 'readonly',
                renderPacksTab: 'readonly',
                previewPack: 'readonly',
                insertPack: 'readonly',

                // ── editor/pricing.js ──
                renderPricing: 'readonly',
                initPricingDrag: 'readonly',
                savePricingOrder: 'readonly',
                initPaymentTermsEditor: 'readonly',
                initSingleLiEditor: 'readonly',
                destroyLiEditor: 'readonly',
                deleteLineItem: 'readonly',
                addLine: 'readonly',
                reRow: 'readonly',
                reTotal: 'readonly',

                // ── editor/tc-library.js ──
                TC_DEFAULTS: 'readonly',
                openTCLib: 'readonly',
                filterTCLib: 'readonly',
                insertTC: 'readonly',

                // ── editor/packages.js ──
                renderPackages: 'readonly',
                getDefaultPackages: 'readonly',
                togglePackages: 'readonly',
                setRecommended: 'readonly',
                addPackageFeature: 'readonly',
                removePackageFeature: 'readonly',
                setFeatureTier: 'readonly',
                collectPackagesData: 'readonly',
                buildPackagesPdfHtml: 'readonly',

                // ── editor/addons.js ──
                renderAddOns: 'readonly',
                addAddOn: 'readonly',
                removeAddOn: 'readonly',
                toggleAddOn: 'readonly',
                calcAddOnsTotal: 'readonly',
                collectAddOnsData: 'readonly',
                buildAddOnsPdfHtml: 'readonly',

                // ── editor/payment-schedule.js ──
                renderPaymentSchedule: 'readonly',
                buildScheduleBarHtml: 'readonly',
                addMilestone: 'readonly',
                removeMilestone: 'readonly',
                toggleScheduleMode: 'readonly',
                updateScheduleBar: 'readonly',
                validateSchedule: 'readonly',
                collectPaymentScheduleData: 'readonly',
                buildSchedulePdfHtml: 'readonly',

                // ── editor/payments.js ──
                PAYMENT_METHODS: 'readonly',
                paymentTotals: 'readonly',
                renderPayments: 'readonly',
                buildPaymentSummaryHtml: 'readonly',
                addPayment: 'readonly',
                removePayment: 'readonly',
                updatePaymentSummary: 'readonly',
                collectPaymentsData: 'readonly',
                paymentStatusBadge: 'readonly',
                buildPaymentsReceiptHtml: 'readonly',
                quickRecordPayment: 'readonly',
                saveQuickPayment: 'readonly',
                showPaymentPickerMenu: 'readonly',

                // ── editor/csv-import.js ──
                buildPricingInsights: 'readonly',
                openCsvImport: 'readonly',
                handleCsvFile: 'readonly',
                detectDelimiter: 'readonly',
                parseCsv: 'readonly',
                autoMapColumns: 'readonly',
                _csvParsed: 'writable',
                _csvMap: 'writable',
                parseCsvInput: 'readonly',
                renderCsvPreview: 'readonly',
                updateCsvMap: 'readonly',
                confirmCsvImport: 'readonly',

                // ── editor/ai-assistant.js ──
                _aiLoading: 'writable',
                AI_PROMPTS: 'readonly',
                aiRequest: 'readonly',
                showAiPanel: 'readonly',
                getEditorContent: 'readonly',
                runAi: 'readonly',
                runAiCustom: 'readonly',
                acceptAiResult: 'readonly',
                renderAiSettingsCard: 'readonly',

                // ── editor/notes.js ──
                renderNotes: 'readonly',
                addNote: 'readonly',
                deleteNote: 'readonly',

                // ── editor/toc.js ──
                renderTOC: 'readonly',
                hideTOC: 'readonly',
                tocGoTab: 'readonly',
                tocGoSection: 'readonly',

                // ── editor/focus-mode.js ──
                toggleFocusMode: 'readonly',
                exitFocusMode: 'readonly',

                // ── export/templates.js ──
                buildPricingHtml: 'readonly',
                buildSenderDetails: 'readonly',
                buildSenderTaxLine: 'readonly',
                buildClientDetails: 'readonly',
                buildBankFooterHtml: 'readonly',
                buildCoverHtml: 'readonly',
                buildModernTpl: 'readonly',
                buildClassicTpl: 'readonly',
                buildMinimalTpl: 'readonly',
                buildTabularTpl: 'readonly',

                // ── export/pdf-templates2.js ──
                buildExecutiveTpl: 'readonly',
                buildCompactTpl: 'readonly',
                buildBoldTpl: 'readonly',
                buildSidebarTpl: 'readonly',
                buildStripeTpl: 'readonly',
                buildFormalTpl: 'readonly',
                buildCleanTpl: 'readonly',
                buildNordTpl: 'readonly',
                buildAmericanTpl: 'readonly',

                // ── export/tpl-data.js ──
                TPLS: 'readonly',
                TPL_CATEGORIES: 'readonly',

                // ── export/preview.js ──
                openPreview: 'readonly',
                closePreview: 'readonly',
                setDocTpl: 'readonly',
                calcTotals: 'readonly',
                editorJsToHtml: 'readonly',
                buildPreview: 'readonly',
                buildAcceptanceBlockHtml: 'readonly',

                // ── export/export.js ──
                doExport: 'readonly',
                bulkSelected: 'writable',
                toggleBulkCheck: 'readonly',
                updateBulkUI: 'readonly',
                toggleSelectAll: 'readonly',
                clearBulkSelection: 'readonly',
                bulkExport: 'readonly',

                // ── export/create.js ──
                createProp: 'readonly',
                dupProp: 'readonly',
                dupPropWithClient: 'readonly',
                doDupWithClient: 'readonly',
                delProp: 'readonly',
                fromTpl: 'readonly',
                fromSavedTpl: 'readonly',
                saveAsTemplate: 'readonly',
                doSaveAsTemplate: 'readonly',
                deleteSavedTpl: 'readonly',
                bumpVersion: 'readonly',
                toggleCover: 'readonly',
                archiveProp: 'readonly',
                unarchiveProp: 'readonly',
                refreshSide: 'readonly',
                showCtx: 'readonly',
                hideCtx: 'readonly',
                ctxAction: 'readonly',

                // ── export/sharing.js ──
                generateShareToken: 'readonly',
                shareProposal: 'readonly',
                copyShareLink: 'readonly',
                getProposalByToken: 'readonly',
                recordProposalView: 'readonly',
                respondToProposal: 'readonly',

                // ── export/email.js ──
                emailProposal: 'readonly',
                sendWithTemplate: 'readonly',

                // ── export/signature.js ──
                initSignaturePad: 'readonly',
                showSignatureCanvas: 'readonly',
                setupSigCanvas: 'readonly',
                clearSigCanvas: 'readonly',
                saveSignature: 'readonly',
                editSignature: 'readonly',
                clearSignature: 'readonly',

                // ── export/integrations.js ──
                exportMarkdown: 'readonly',
                editorJsToMarkdown: 'readonly',
                stripHtml: 'readonly',
                exportCsv: 'readonly',
                exportStandaloneHtml: 'readonly',
                sendWebhook: 'readonly',
                showExportMenu: 'readonly',
                downloadBlob: 'readonly',
                slugify: 'readonly',

                // ── export/derivatives.js ──
                generateDerivative: 'readonly',
                openDerivativesMenu: 'readonly',
                buildSowHtml: 'readonly',
                buildContractHtml: 'readonly',
                buildReceiptHtml: 'readonly',
                buildSignatureBlock: 'readonly',

                // ── export/diff-view.js ──
                openDiffView: 'readonly',
                updateDiffView: 'readonly',
                renderSnapshotHtml: 'readonly',
                computeChanges: 'readonly',

                // ── boot.js ──
                initApp: 'readonly',
                bootApp: 'readonly',
                lucideScope: 'readonly',
                patchAriaLabels: 'readonly',
                APP_VERSION: 'readonly',
                APP_BUILD: 'readonly',
                WHATS_NEW_ITEMS: 'readonly',
                checkWhatsNew: 'readonly',
                showWhatsNew: 'readonly',
                dismissWhatsNew: 'readonly',
                checkNpsPrompt: 'readonly',
                showNpsPrompt: 'readonly',
                submitNpsScore: 'readonly',
                closeNpsPrompt: 'readonly',
            },
        },
        rules: {
            'no-var': 'error',
            'eqeqeq': ['error', 'always', { null: 'ignore' }],
            'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_', caughtErrors: 'none' }],
            'no-console': ['warn', { allow: ['warn', 'error'] }],
            'no-debugger': 'error',
            'prefer-const': 'warn',
            'no-undef': 'error',
            'no-redeclare': 'off', // Global-scope scripts redefine shared globals — not useful here
            'no-empty': ['error', { allowEmptyCatch: true }], // Intentional catch-and-swallow pattern
            'no-constant-condition': ['error', { checkLoops: false }],
        },
    },
    // client.js and landing.js are standalone — ignore unused-vars from onclick handlers
    {
        files: ['assets/js/client.js', 'assets/js/landing.js'],
        rules: {
            'no-unused-vars': 'off',
        },
    },
];
